version: '3'

services:

  web:
    build: 
      context: .
      dockerfile: images/web
      args:
        apache_document_root: ${APACHE_DOCUMENT_ROOT}
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ${APP_WWW}:${WORKING_DIR}
      - ${APP_HOSTS}:/etc/apache2/sites-available
      - ${APP_LOGS}:/var/log/apache2
    working_dir: ${WORKING_DIR}      
    ports:
      - 8080:80
      - 3000:3000
      - 3001:3001
    extra_hosts:
      - "site1:127.0.0.1"
      - "site2:127.0.0.1"      

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ${APP_DB}:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    environment:
#     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8181:80
#    volumes:
#     - /sessions
#     - ~/docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
#     - /custom/phpmyadmin/theme/:/www/themes/them

#  node:
#    image: node
#    user: "node"
#    environment:
#      - NODE_ENV=dev
#    volumes:
#      - ${APP_WWW}:${WORKING_DIR}
#    working_dir: ${WORKING_DIR}
#    command: npm run watch
#    ports:
#      - 3000:3000
#      - 3001:3001